# https://taskfile.dev

version: '3'

vars:
  PLUGIN_NAME: gfwreport
  BINARY_NAME: caddy
  BUILD_DIR: build

tasks:
  # Code formatting and linting
  gofmt:
    desc: Format Go code
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  gci:
    desc: Format imports
    cmds:
      - go install github.com/daixiang0/gci@v0.13.1
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/ysicing/caddy2-extra)" -s default -s blank -s dot .

  golint:
    desc: Run golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
      - golangci-lint run -v ./...

  govulncheck:
    desc: Run vulnerability detection
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@v1.1.1
      - govulncheck ./...

  fmt:
    desc: Format code and run security checks
    run: once
    cmds:
      - task: gofmt
      - task: gci
      - task: govulncheck

  # Testing
  test:
    desc: Run unit tests
    dir: gfwreport
    cmds:
      - go test -v ./...

  build:
    desc: Build Caddy with GFWReport and DNS plugins
    cmds:
      - command -v xcaddy || go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - xcaddy build
          --with github.com/ysicing/caddy2-extra=../caddy2-extra
          --with github.com/caddy-dns/cloudflare
          --with github.com/caddy-dns/tencentcloud
          --with github.com/caddy-dns/alidns
      - ./caddy list-modules

  run:
    desc: Run with local config
    cmds:
      - task: build
      - ./caddy run --config ./Caddyfile.local --adapter caddyfile

  validate:
    desc: Validate configuration files
    cmds:
      - task: build
      - ./caddy validate --config examples/basic-config.Caddyfile --adapter caddyfile
      - ./caddy validate --config examples/advanced-config.Caddyfile --adapter caddyfile

  # Utilities
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf caddy

  # Default task
  default:
    desc: Clean and build
    cmds:
      - task: clean
      - task: build
