version: '3.8'

services:
  # Main Caddy server with GFWReport plugin
  caddy:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Admin API
    volumes:
      # Configuration files
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./patterns:/etc/caddy/patterns:ro
      - ./scripts:/usr/local/bin/scripts:ro
      
      # Data persistence
      - caddy_data:/data
      - caddy_config:/config
      
      # Logs
      - ./logs:/var/log/caddy
      
      # Web content
      - ./www:/var/www/html:ro
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    restart: unless-stopped
    depends_on:
      - webhook-receiver
    networks:
      - caddy-network

  # Example webhook receiver for testing
  webhook-receiver:
    image: python:3.9-alpine
    ports:
      - "9090:9090"
    volumes:
      - ./webhook-server.py:/app/server.py:ro
    working_dir: /app
    command: python server.py
    networks:
      - caddy-network

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy-network:
    driver: bridge
